---
title: Louis-André Labadie – Digital designer
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: monsieur@louis-andre.net
description: 'If you''re looking for information about Louis-André Labadie, this is
  an excellent place to start. I am he, and this is my site!

'
baseurl: ''
url: http://louis-andre.net
twitter_username: lalabadie
github_username: l-a
markdown: kramdown
languages:
- en
- fr
exclude_from_localizations:
- assets
- js
- css
permalink: "/journal/:title/"
